/* generated by rpcoder */

package foo.bar
{
    public class Mail
    {
        private var _subject:String;
        private var _body:String;

        public function get subject():String
        {
            return _subject;
        }

        public function get body():String
        {
            return _body;
        }

        public function Mail(object:Object = null)
        {
            if (object)
            {
                _subject = object['subject'];
                _body = object['body'];
            }
        }

        public function toString():String
        {
            return [_subject, _body].join(', ');
        }
    }
}
